### PR TITLE
Fix/this context in controller

### LINKED ISSUE #17: Wrong this context inside a route method
`this` is undefined inside a route method.

Instantiate the controller and use it as this controller? But needs to be scoped for all route methods.

### LINKED ISSUE #18: Rename functions and vars
const -> UPPER_SNAKE_CASE
validator functions -> camelCase

### PR DESCRIPTION
**Pull request by buehler**
- fixes #17 wrong this context in routes. uses instance of controller for registered routes now.
- fixes #18 rename const vars and validators to correct cases

### CODE REVIEW

File: controllers/ControllerDecorator.ts [hunk 1]
```diff
@@ -1,13 +1,59 @@
...
+import {ErrorHandlerManager, ERRORHANDLER_KEY} from '../errors/ErrorHandlerDecorator';
+import httpStatus = require('http-status');
 
 let controllers: ControllerRegistration[] = [],
     definedRoutes = [];
 
+const primitiveTypes = [Object, String, Array, Number, Boolean],
+    nonJsonTypes = [String, Number, Boolean];
+
+const defaultErrorHandler = (req, res, err) => {
```
Comment (dwirz) [inline controllers/ControllerDecorator.ts]: Why not move this into ErrorHandlerDecorator or into the errors folder/package?

Comment (buehler) [inline controllers/ControllerDecorator.ts]: It's a private variable (const) during the decoration magic :-)

File: controllers/ControllerDecorator.ts [hunk 2]
```diff
@@ -1,13 +1,59 @@
...
+    console.error(err);
+    res.status(httpStatus.INTERNAL_SERVER_ERROR).end();
+};
+
+let parseParam = (value: any, param: Param) => {
```
Comment (dwirz) [inline controllers/ControllerDecorator.ts]: ParamDecorators or params folder/package?

Comment (buehler) [inline controllers/ControllerDecorator.ts]: same as with `defaultErrorHandler`

File: controllers/ControllerDecorator.ts [hunk 3]
```diff
@@ -42,32 +88,112 @@ export function registerControllers(baseUrl: string = '', router: Router = Route
...
+                                return;
+                            case ParamType.Header:
+                                paramValues[p.index] = parseParam(request.get(p.name), p);
+                                return;
+                        }
+                    });
+                } catch (e) {
+                    errorHandlers.callHandlers(request, response, e);
+                    return;
+                }
```
Comment (dwirz) [inline controllers/ControllerDecorator.ts:177]: I would extract this whole try-catch-block (or at least the try-block) to a buildParamValues-function. Just for readability.

File: controllers/ControllerDecorator.ts [hunk 4]
```diff
@@ -42,32 +88,112 @@ export function registerControllers(baseUrl: string = '', router: Router = Route
...
+                        throw new WrongReturnTypeError(route.propertyKey, returnType, result.constructor);
+                    }
+                    if (returnType === Promise) {
+                        (result as Promise<any>).then(responseFunction, err => errorHandlers.callHandlers(request, response, new RouteError(route.propertyKey, err)));
+                    } else {
+                        responseFunction(result);
+                    }
+                } catch (e) {
+                    errorHandlers.callHandlers(request, response, new RouteError(route.propertyKey, e));
+                }
```
Comment (dwirz) [inline controllers/ControllerDecorator.ts:204]: Same as above... extract for readability....

File: controllers/ControllerDecorator.ts (hunk 1 above)
Comment (buehler) [inline controllers/ControllerDecorator.ts]: 5ae5bda

File: controllers/ControllerDecorator.ts (hunk 2 above)
Comment (buehler) [inline controllers/ControllerDecorator.ts]: I moved the default error handler, but I'd rather not move the parseParam function, since it's private only for this module

File: controllers/ControllerDecorator.ts (hunk 4 above)
Comment (buehler) [inline controllers/ControllerDecorator.ts:204]: this is a conditional return, cannot be extracted :/

File: controllers/ControllerDecorator.ts (hunk 3 above)
Comment (buehler) [inline controllers/ControllerDecorator.ts:177]: 31f17af
